#!/usr/bin/bash env
# Made by Facundo Diaz for Holberton School
sudo apt-get -y update
sudo apt-get -y install nginx
newstring="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "26i $newstring" /etc/nginx/sites-available/default
sudo service nginx restart
