#!/usr/bin/env bash
# Made by Facundo Diaz for Holberton School 2021


sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen webapp 0.0.0.0:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 210-web-01 35.190.156.123:80 check\n\tserver 210-web-02 35.237.57.199:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
