#!/usr/bin/env bash
# Made by Facundo Diaz for Holberton School 2021

apt-get -y update
apt-get -y install haproxy=1.6.\*
echo -e "\nbackend web-backend\n\tbalance roundrobin\n\tserver web1 35.190.156.123:80 check\n\tserver web2 35.237.57.199:80 check\n" >> /etc/haproxy/haproxy.cfg
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n" >> /etc/haproxy/haproxy.cfg
service haproxy restart

