#!/usr/bin/env bash
# Made by Facundo Diaz for Holberton School 2021

sudo rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start