#!/usr/bin/env bash

# Made by Facundo Diaz to Holberton School

# This script that displays the content of the file /etc/passwd

while read line
do
	echo "$line" | cut -d":" -f1,3,6
done < /etc/passwd