#!/usr/bin/env bash

# Made by Facundo Diaz to Holberton School

# This script is displaying "Holberton School" 10 times
x=0
b=10
while [ "$x" -lt "$b" ]
do
  echo "Holberton School"
  x=$(( x + 1 ))
done