#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
x=0
b=10
while [ "$x" -lt "$b" ]
do
  if [ "$x" -eq "9" ]
  then
  echo "Hi"
  fi
  echo "Holberton School"
  x=$(( x + 1 ))
done