#!/usr/bin/env bash

# Made by Facundo Diaz to Holberton School

# This script is  displaying numbers from 1 to 20 and 
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration

x=1
while [ $x -lt 21 ]
do
    echo "$x"
    case $x in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
    x=$(( x + 1 ))
done