#!/usr/bin/env bash

# Made by Facundo Diaz to Holberton School

# This script displays the content of the current directory in a list format
# where only the part of the name after the first dash is displayed

for eachfile in *
do
   eachfile=$(echo "$eachfile" | cut -d'-' -f 2)
   echo "$eachfile"
done